/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graZWynikami1;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Jowik
 */
public class GraPanelGlowny extends javax.swing.JPanel {

    /**
     * Creates new form GraPanelGlowny
     */
    public GraPanelGlowny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        guzikGraj = new javax.swing.JButton();
        guzikWyniki = new javax.swing.JButton();
        Anuluj = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\nWitaj w grze \"Zgadnij, jaka to liczba\". Gra rozpocznie się po kliknięciu guzika \"Graj\". Możesz też obejrzeć wyniki klikając drugi guzik");
        jScrollPane2.setViewportView(jTextArea2);

        guzikGraj.setText("Graj");
        guzikGraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikGrajActionPerformed(evt);
            }
        });

        guzikWyniki.setText("Wyniki");

        Anuluj.setText("Anuluj");
        Anuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(guzikGraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Anuluj)
                .addGap(18, 18, 18)
                .addComponent(guzikWyniki)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guzikGraj)
                    .addComponent(guzikWyniki)
                    .addComponent(Anuluj))
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guzikGrajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikGrajActionPerformed
        Random random = new Random();
        int r = random.nextInt(10);
        int liczba=21;
        int wynik;
        String wiadomosc="";
        JOptionPane.showMessageDialog(null, "Komputer teraz wylosuje liczbę od 1-20. Sprónuj ją zgadnąć");
                
        while(liczba!=r){
            String liczbaUzytkownika=Liczbowa.poprosOLiczbe(wiadomosc+ " Podaj liczbę od 1 do 20");
            if (liczbaUzytkownika==null) System.exit(1);
            if (Liczbowa.isInt(liczbaUzytkownika)){
                liczba=Integer.parseInt(liczbaUzytkownika);
                wiadomosc=Liczbowa.sprawdzLiczbe(r,liczba);
                Wynik.counter++;
                System.out.println(Wynik.counter);
            } else {
                wiadomosc = "Podałeś nieprawidłową liczbę, spróbuj jeszcze raz";
            }    
        }
        if (liczba==r&&!wiadomosc.equals("")){
            wynik=Wynik.counter;
            JOptionPane.showMessageDialog(null, wiadomosc+" Liczba ruchów: "+wynik);
            Wynik.counter=1;
        }
        
        
    }//GEN-LAST:event_guzikGrajActionPerformed

    private void AnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnulujActionPerformed
        System.exit(1);
    }//GEN-LAST:event_AnulujActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anuluj;
    private javax.swing.JButton guzikGraj;
    private javax.swing.JButton guzikWyniki;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
